#!/bin/bash

sudo apt update -y 
sudo apt upgrade -y

# install software packages from dnf
sudo apt install -y focuswriter flatpak deluge htop neofetch zsh nodejs gnome-tweaks php ssh

# install software packages from flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install -y postman flathub org.gnome.Extensions com.spotify.Client com.discordapp.Discord

# os configuration
# mouse acceleration -- flat
gsettings  set  org.gnome.desktop.peripherals.mouse  accel-profile  flat

# fractional scaling
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

# zsh as default shell (requires restart)
chsh -s $(which zsh)

# set login screen to main monitor
sudo cp ~/.config/monitors.xml ~gdm/.config/monitors.xml
sudo chown gdm:gdm ~gdm/.config/monitors.xml

# run and enable ssh server
sudo systemctl start sshd
sudo systemctl enable sshd

# install oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install zsh autosuggestion plugin
sudo git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
