#!/bin/bash

sudo apt update -y 
sudo apt upgrade -y

# install software packages from apt
sudo apt install -y focuswriter focuswriter flatpak deluge chromium htop neofetch zsh gnome-tweaks vim-enhanced

# install software packages from flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install -y postman flathub org.gnome.Extensions com.spotify.Client com.discordapp.Discord

# os configuration
# mouse acceleration -- flat
gsettings  set  org.gnome.desktop.peripherals.mouse  accel-profile  flat

# zsh as default shell (requires restart)
chsh -s $(which zsh)

# run and enable ssh server
sudo systemctl start sshd
sudo systemctl enable sshd

# install oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install zsh autosuggestion plugin
sudo git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# install node version manager 
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
