-- copilot setup
-- require("copilot").setup({
--   copilot_model = "claude-sonnet-4.5",
--   suggestion = {
--     keymap = {
--       accept = "<C-a>",
--       next = "<C-j>",
--       previous = "<C-J>",
--     },
--   },
-- })
